
function SBChart()
{};SBChart.getChart=function(strID)
{if(typeof document.SBHE_allElement=='undefined')
return null;return document.SBHE_allElement.m_htCollection[strID];};SBChart.DEF=function()
{};SBChart.UT=function()
{};SBChart.CT=function()
{};SBChart.DS=function()
{};SBChart.DEF.__LANGUAGE="kr";SBChart.DEF.__chromeFrame=false;SBChart.DEF.__useBinding=false;var agt=navigator.userAgent.toLowerCase();SBChart.DEF.is_major=parseInt(navigator.appVersion);SBChart.DEF.is_minor=parseFloat(navigator.appVersion);SBChart.DEF.is_moz=((agt.indexOf('mozilla')!=-1)&&(agt.indexOf('spoofer')==-1)&&(agt.indexOf('compatible')==-1)&&(agt.indexOf('opera')==-1)&&(agt.indexOf('webtv')==-1)&&(agt.indexOf('hotjava')==-1));SBChart.DEF.is_moz2=(SBChart.DEF.is_moz&&(SBChart.DEF.is_major==2));SBChart.DEF.is_moz3=(SBChart.DEF.is_moz&&(SBChart.DEF.is_major==3));SBChart.DEF.is_moz4=(SBChart.DEF.is_moz&&(SBChart.DEF.is_major==4));SBChart.DEF.is_gecko=(agt.indexOf('gecko')!=-1);SBChart.DEF.is_firefox=(agt.indexOf('firefox')!=-1);SBChart.DEF.is_nav2=SBChart.DEF.is_moz2;SBChart.DEF.is_nav3=SBChart.DEF.is_moz3;SBChart.DEF.is_nav4=SBChart.DEF.is_moz4;SBChart.DEF.is_nav4up=(SBChart.DEF.is_nav4||((SBChart.DEF.is_major>=4)&&(agt.indexOf("netscape")!=-1)));SBChart.DEF.is_nav=(SBChart.DEF.is_nav2||SBChart.DEF.is_nav3||SBChart.DEF.is_nav4);SBChart.DEF.is_mozilla=(SBChart.DEF.is_moz&&SBChart.DEF.is_gecko);SBChart.DEF.is_mozilla1=(SBChart.DEF.is_moz&&SBChart.DEF.is_gecko&&(agt.indexOf("rv:1")!=-1));SBChart.DEF.is_ie=((agt.indexOf("msie")!=-1)&&(agt.indexOf("opera")==-1));SBChart.DEF.is_ie6=(SBChart.DEF.is_ie&&(SBChart.DEF.is_major==4)&&(agt.indexOf("msie 6.")!=-1));SBChart.DEF.is_ie7=(SBChart.DEF.is_ie&&(SBChart.DEF.is_major==4)&&(agt.indexOf("msie 7.")!=-1));if(SBChart.DEF.is_ie7){SBChart.DEF.is_ie6=false;}
SBChart.DEF.is_ie8=(SBChart.DEF.is_ie&&(SBChart.DEF.is_major==4)&&(agt.indexOf("msie 8.")!=-1));if(SBChart.DEF.is_ie8){SBChart.DEF.is_ie6=false;SBChart.DEF.is_ie7=false;}
SBChart.DEF.is_ie9=(SBChart.DEF.is_ie&&(SBChart.DEF.is_major==5)&&(agt.indexOf("msie 9.")!=-1));if(SBChart.DEF.is_ie9){SBChart.DEF.is_ie6=false;SBChart.DEF.is_ie7=false;SBChart.DEF.is_ie8=false;SBChart.DEF.is_ie10=false;}
SBChart.DEF.is_ie10=(SBChart.DEF.is_ie&&(SBChart.DEF.is_major==5)&&(agt.indexOf("msie 10.")!=-1));if(SBChart.DEF.is_ie10){SBChart.DEF.is_ie6=false;SBChart.DEF.is_ie7=false;SBChart.DEF.is_ie8=false;SBChart.DEF.is_ie9=false;}
SBChart.DEF.is_ie11=((SBChart.DEF.is_major==5)&&(agt.indexOf("trident/7.0")!=-1)&&(agt.indexOf("rv:11.")!=-1));if(SBChart.DEF.is_ie11){SBChart.DEF.is_ie6=false;SBChart.DEF.is_ie7=false;SBChart.DEF.is_ie8=false;SBChart.DEF.is_ie9=false;SBChart.DEF.is_ie10=false;}
SBChart.DEF.is_opera=(agt.indexOf("opera")!=-1);SBChart.DEF.is_safari=((agt.indexOf('safari')!=-1));SBChart.DEF.is_chrome=!SBChart.DEF.is_ie&&(agt.indexOf("chrome")!=-1)?true:false;SBChart.DEF.is_crOs=SBChart.DEF.is_chrome&&(agt.indexOf("csos")!=-1);SBChart.DEF.is_chromeFrame=!SBChart.DEF.is_ie&&SBChart.DEF.is_chrome&&SBChart.DEF.__chromeFrame;SBChart.DEF.is_webkit=SBChart.DEF.is_safari||SBChart.DEF.is_chrome;SBChart.DEF.is_mozBrowser=SBChart.DEF.is_firefox||SBChart.DEF.is_opera;SBChart.DEF.is_ipad=(SBChart.DEF.is_safari&&(agt.indexOf('ipad')!=-1));SBChart.DEF.is_iphone=(SBChart.DEF.is_safari&&(agt.indexOf('iphone')!=-1));SBChart.DEF.is_apple=(SBChart.DEF.is_ipad||SBChart.DEF.is_iphone);SBChart.DEF.is_android=(agt.indexOf('android')!=-1);SBChart.DEF.is_opera_mini=(agt.indexOf('opera mini')!=-1);SBChart.DEF.is_smartphone=false;function createSBChart(grid,objJson){var attrs={id:"sbchart1",parentId:"sbChartArea",margin:{left:50,top:20,right:50,bottom:20},width:950,height:500,colors:["#ff3b30","#ff9500","#ffcc00","#4cd964","#34aadc","#007aff","#5856d6","#ff2d55","#7ECA8F","#E48A70","#75C165","#F3c47c"],jsonRef:"grid_data",category:"",label:{},title:"",animate:true,shapePoint:true,data:[{keys:[],type:"bar",lineType:"line",labelType:"value",axis:"y"},{keys:[],type:"",axis:"y2"}],axis:{x:{show:true,orient:"bottom"},y:{show:true,orient:"left",ticks:10,tickFormat:".1",text:""},y2:{show:false,orient:"left",ticks:10,tickFormat:".1",text:""}},legend:{show:true,position:"right",},tooltip:true};attrs=$.extend(true,attrs,objJson);attrs.keys=[];attrs.labels=[];attrs.shapes={};var keyList=[];var keyCheck={};for(var i=0;i<attrs.data.length;i++){var keys=attrs.data[i].keys;if(keys==undefined||keys==null||keys.length==0)
continue;for(var j=0;j<keys.length;j++){if(!keyCheck[keys[j]]){keyList.push(keys[j]);keyCheck[keys[j]]=true;}};}
if(grid){if(attrs.jsonRef==undefined||attrs.jsonRef==null||attrs.jsonRef=="")
attrs.jsonRef=grid.m_strGridJsonReg;attrs.grid=grid;var captions=grid.attribute["caption"].split("^");var caption={};for(var i=0;i<grid.m_arColumn.length;i++){var col=grid.m_arColumn[i].attribute["ref"];caption[col]=captions[i];}
if(keyList.length==0){for(var i=0;i<grid.m_arColumn.length;i++){var col=grid.m_arColumn[i].attribute["ref"];if(attrs.category==col)
continue;attrs.label[col]=captions[i];attrs.keys.push(col);attrs.labels.push(captions[i]);}}else{for(var i=0;i<keyList.length;i++){var key=keyList[i];if(attrs.category==key)
continue;attrs.label[key]=caption[key];attrs.keys.push(key);attrs.labels.push(caption[key]);}}}
var shapes=['circle','cross','triangle-up','diamond','square','triangle-down'];if(attrs.labels==undefined||attrs.labels==null||attrs.labels.length==0){for(var j=0;j<keyList.length;j++){if(attrs.category==keyList[j])
continue;if(attrs.label[keyList[j]]===undefined)
attrs.label[keyList[j]]=keyList[j];attrs.keys.push(keyList[j]);attrs.labels.push(keyList[j]);attrs.shapes[keyList[j]]=shapes[j%6];};}
attrs.titleHeight=0;if(attrs.title!="")
attrs.titleHeight=SBChart.DEF.TITLE_HEIGHT;if(attrs.colors.length>attrs.keys.length)
attrs.colors=attrs.colors.slice(0,attrs.keys.length);return new SBChart.CT.Chart(attrs);};SBChart.DEF.DATA_VERTICAL=0;SBChart.DEF.DATA_HORIZONTAL=1;SBChart.DEF.TITLE_HEIGHT=30;var tip;SBChart.CT.Chart=function(attrs){this.attrs=attrs;this.margin=attrs.margin;this.width=attrs.width-attrs.margin.left-attrs.margin.right,this.height=attrs.height-attrs.margin.top-attrs.margin.bottom;this.titleHeight=attrs.titleHeight;this.x=d3.scale.ordinal().rangeRoundBands([0,this.width],.1);this.y=d3.scale.linear().rangeRound([this.height,this.titleHeight]);this.y2=d3.scale.linear().rangeRound([this.height,this.titleHeight]);this.xAxis=d3.svg.axis().scale(this.x).orient(attrs.axis.x.orient);this.yAxis=d3.svg.axis().scale(this.y).orient(attrs.axis.y.orient);this.yAxis2=d3.svg.axis().scale(this.y2).orient(attrs.axis.y2.orient);this.colors=d3.scale.ordinal().range(attrs["colors"]);this.colors.domain(this.attrs.keys);var viewBox="0 0 "+String(attrs.width+50)+" "+String(attrs.height);this.svg=d3.select("#"+attrs.parentId).append("svg").attr("id",attrs.id).attr("viewBox",viewBox).attr("preserveAspectRatio","xMinYMin slice").attr("width",this.width+attrs.margin.left+attrs.margin.right).attr("height",this.height+attrs.margin.top+attrs.margin.bottom).append("g").attr("transform","translate("+attrs.margin.left+","+attrs.margin.top+")");this.chartObject=null;tip=d3.tip().attr('class','d3-tip').offset([-10,0]).html(function(d){var percent=d.percent?" ("+d.percent.toFixed(0)+"%)":"";return"<strong>"+d.label+" :</strong> <span style='color:red'>"+d.value+percent+"</span>";});this.svg.call(tip);};SBChart.CT.Chart.prototype.createData=function(type){var data=eval(this.attrs.jsonRef);var names=this.attrs.columns;var key=this.attrs.key;var keys=this.attrs.keys;var label=this.attrs.label;var category=this.attrs.category;if(type==SBChart.DEF.DATA_VERTICAL){return keys.map(function(key){return{key:key,category:label[category],values:data.map(function(d){return{key:key,label:label[key],value:+d[key],category:d[category]};})};});}else if(type==SBChart.DEF.DATA_HORIZONTAL){return data.map(function(d){return{values:category.map(function(category){return{category:label[category],label:label[category],value:+d[category]};}),category:d[category]};return v;});}else{return names.map(function(name){return{name:name,values:data.map(function(d){return{name:name,label:keys[name],value:+d[name],key:d[key]};})};});}};SBChart.CT.Chart.prototype.createBarData=function(type){var data=eval(this.attrs.jsonRef);var keys=this.attrs.keys;var label=this.attrs.label;var category=this.attrs.category;if(type==SBChart.DEF.DATA_VERTICAL){return data.map(function(d){return{values:keys.map(function(key){return{key:key,label:label[key],value:+d[key]};}),category:d[category]};return v;});}else{}};SBChart.CT.Chart.prototype.createChart=function(type){this.clearAll();this.drawTitle();var y2=this.attrs.axis.y2.show;if(type=="bar")
this.barChart();else if(type=="vbar")
this.verticalBarChart();else if(type=="sbar")
this.stackedBarChart();else if(type=="nsbar")
this.normalStackedBarChart();else if(type=="vsbar")
this.verticalStackedBarChart();else if(type=="vnsbar")
this.verticalNormalStackedBarChart();else if(type=="line")
this.lineChart("line");else if(type=="sline")
this.lineChart("sline");else if(type=="spline")
this.lineChart("cardinal");else if(type=="area")
this.areaChart();else if(type=="sarea")
this.stackedAreaChart("zero");else if(type=="strm")
this.stackedAreaChart("wiggle");else if(type=="pie")
this.pieChart();else if(type=="donut")
this.donutChart();else if(type=="multi"){this.multiChart();}else if(type=="multi2"){this.attrs.data[0].type="sbar";this.attrs.axis.y2.show=true;this.multiChart();this.attrs.axis.y2.show=y2;}else if(type=="scatter"){this.scatterChart();}};SBChart.CT.Chart.prototype.clearAll=function(){this.svg.selectAll("*").remove();};SBChart.CT.Chart.prototype.drawAxis=function(){if(this.attrs.axis.x.show==true){var xAxis=this.svg.select("g.x.axis");if(xAxis[0][0]){xAxis.transition().duration(1500).ease("sin-in-out").call(this.xAxis);}else{this.svg.append("g").attr("class","x axis").attr("transform","translate(0,"+this.height+")").call(this.xAxis);}}
if(this.attrs.axis.y.show==true){var yAxis=this.svg.select("g.y.axis");if(yAxis[0][0]){yAxis.transition().duration(1500).ease("sin-in-out").call(this.yAxis);}else{this.svg.append("g").attr("class","y axis").call(this.yAxis).append("text").attr("transform","rotate(-90)").attr("y",6).attr("x",-this.titleHeight).attr("dy",".71em").style("text-anchor","end").text(this.attrs.axis.y.text).attr("y");}}
if(this.attrs.axis.y2.show==true){var yAxis2=this.svg.select("g.y2.axis");if(yAxis2[0][0]){yAxis2.transition().duration(1500).ease("sin-in-out").call(this.yAxis2);}else{this.svg.append("g").attr("class","y2 axis").call(this.yAxis2).attr("transform","translate("+this.width+",0)");}}};SBChart.CT.Chart.prototype.drawVerticalAxis=function(xAxis,yAxis){if(this.attrs.axis.x.show==true){var xAxisEx=this.svg.select("g.x.axis");if(xAxisEx[0][0]){xAxisEx.transition().duration(1500).ease("sin-in-out").call(xAxis);}else{this.svg.append("g").attr("class","x axis").attr("transform","translate(0,"+this.height+")").call(xAxis).append("text").attr("y",-20).attr("x",this.width).attr("dy",".71em").style("text-anchor","end").text(this.attrs.axis.y.text);}}
if(this.attrs.axis.y.show==true){var yAxisEx=this.svg.select("g.y.axis");if(yAxisEx[0][0]){yAxisEx.transition().duration(1500).ease("sin-in-out").call(yAxis);}else{this.svg.append("g").attr("class","y axis").call(yAxis);}}};SBChart.CT.Chart.prototype.drawLegend=function(names,event){if(this.attrs.legend.show==false)
return;var attrs=this.attrs;var legend=this.svg.selectAll(".legend").data(names.slice()).enter().append("g");if(this.attrs.shapePoint==true){var colors=this.colors;var shapes=this.attrs.shapes;var width=this.width;var titleHeight=this.titleHeight;if(this.attrs.legend.position=="right"){legend.attr("class","legend").attr("transform",function(d,i){return"translate(55,"+(i*20+titleHeight)+")";});legend.append("path").attr("class","point").attr("d",d3.svg.symbol().type(function(d){return shapes[d];})).attr("transform",function(d){return"translate("+(width-4)+", 6 )";}).style("fill",function(d){return colors(d);}).style("stroke","grey").style("stroke-width","1px");legend.append("text").attr("x",this.width-12).attr("y",6).attr("dy",".35em").style("text-anchor","end").text(function(d){return attrs.label[d];});}else if(this.attrs.legend.position=="bottom"){}else{return;}}else{if(this.attrs.legend=="right"){legend.attr("class","legend").attr("transform",function(d,i){return"translate(55,"+i*20+")";});legend.append("rect").attr("x",this.width-10).attr("width",10).attr("height",10).style("fill",this.colors).style("stroke","grey");legend.append("text").attr("x",this.width-12).attr("y",6).attr("dy",".35em").style("text-anchor","end").text(function(d){return attrs.label[d];});}else{legend.attr("class","legend").attr("transform",function(d,i){return"translate(55,"+i*20+")";});legend.append("rect").attr("x",this.width-10).attr("width",10).attr("height",10).style("fill",this.colors).style("stroke","grey");legend.append("text").attr("x",this.width-12).attr("y",6).attr("dy",".35em").style("text-anchor","end").text(function(d){return attrs.label[d];});}}
legend.style("opacity",.9);if(event==true){legend.on("mouseover",function(d){d3.select("body").style("cursor","pointer");});legend.on("mouseout",function(d){d3.select("body").style("cursor","default");});legend.on("click",function(d){var opacity=d3.select(this).style("opacity");if(opacity>.5){d3.selectAll("#"+d+" ").transition().duration(500).style("opacity",0);d3.select(this).style("opacity",.2);}else{d3.selectAll("#"+d).transition().duration(1000).style("opacity",.9);d3.select(this).style("opacity",.9);}});}};SBChart.CT.Chart.prototype.drawTitle=function(){var title=this.svg.append("text");title.attr("x",this.width/2).attr("y",6).attr("dy",".35em").style("text-anchor","middle").text(this.attrs.title);};SBChart.CT.Chart.prototype.drawSeriesPoint=function(series){var x=this.x;var y=this.y;var colors=this.colors;var shapes=this.attrs.shapes;var points=null;if(this.attrs.shapePoint==true){points=series.selectAll(".point").data(function(d){return d.values;}).enter().append("path").attr("class","point").attr("d",d3.svg.symbol().type(function(d){return shapes[d.key];})).attr("transform",function(d){var cx=x(d.category)+x.rangeBand()/2;var cy=d.y0&&d.y?y(d.y0+d.y):y(d.value);return"translate("+cx+","+cy+")";}).style("fill",function(d){return colors(d.key);}).style("stroke","grey").style("stroke-width","1px");}else{points=series.selectAll(".point").data(function(d){return d.values;}).enter().append("circle").attr("class","point").attr("cx",function(d){return x(d.category)+x.rangeBand()/2;}).attr("cy",function(d){return y(d.value);}).attr("r","1px").style("fill",function(d){return colors(d.key);}).style("stroke","grey").style("stroke-width","1px");}
if(this.isAnimate()){points.style("opacity",0);points.transition().delay(500).duration(1000).style("opacity",.9);}
this.setTooltip(points);};SBChart.CT.Chart.prototype.isAnimate=function(){return this.attrs.animate;};SBChart.CT.Chart.prototype.setTooltip=function(tag){if(tag==null)
return;if(this.attrs.tooltip==false)
return;tag.on("mouseover",function(d){var o=d3.select(this).style("opacity");if(o<.5)
return;tip.show(d);}).on("mouseout",tip.hide);};SBChart.CT.Chart.prototype.onResize=function(){var aspect=855/450,chart=$("#thesvg");var targetWidth=chart.parent().width();chart.attr("width",targetWidth);chart.attr("height",targetWidth/aspect);};SBChart.CT.Chart.prototype.lineChart=function(type){var svg=this.svg;var x=this.x;var y=this.y;var colors=this.colors;this.yAxis.tickFormat(d3.format(".2s"));var line=d3.svg.line().interpolate(type).x(function(d){return x(d.category)+x.rangeBand()/2;}).y(function(d){return y(d.value);});if(type=="sline"){var seriesData=this.createData(SBChart.DEF.DATA_HORIZONTAL);}else{var seriesData=this.createData(SBChart.DEF.DATA_VERTICAL);}
x.domain(seriesData[0].values.map(function(d){return d.category;}));this.y.domain([0,d3.max(seriesData,function(c){return d3.max(c.values,function(d){return d.value;});})]);var series=svg.selectAll(".series").data(seriesData).enter().append("g").attr("class","series").attr("id",function(d){return d.key;});series.append("path").attr("class","line").attr("d",function(d){return line(d.values);}).style("stroke",function(d){return colors(d.key);}).style("stroke-width","4px").style("fill","none");var lines=svg.selectAll(".line");if(this.isAnimate()==true){lines.attr("stroke-dasharray",function(d){var totalLength=this.getTotalLength();return totalLength+" "+totalLength;}).attr("stroke-dashoffset",function(d){return this.getTotalLength();}).transition().duration(1000).ease("linear").attr("stroke-dashoffset",0);}
this.drawSeriesPoint(series);this.drawAxis();this.drawLegend(this.attrs.labels,true);this.refresh=this;};SBChart.CT.Chart.prototype.barChart=function(){var data=eval(this.attrs.jsonRef);var svg=this.svg;var x=this.x;var y=this.y;var height=this.height;var x1=d3.scale.ordinal();var colors=this.colors;var keys=this.attrs.keys;this.yAxis.tickFormat(d3.format(".2s"));var seriesData=this.createBarData(SBChart.DEF.DATA_VERTICAL);x.domain(seriesData.map(function(d){return d.category;}));x1.domain(keys).rangeRoundBands([0,x.rangeBand()]);y.domain([0,d3.max(seriesData,function(d){return d3.max(d.values,function(d){return d.value;});})]);var group=svg.selectAll(".g").data(seriesData).enter().append("g").attr("class","g").attr("transform",function(d){return"translate("+x(d.category)+",0)";});var rect=group.selectAll("rect").data(function(d){return d.values;}).enter().append("rect").attr("class","bar").attr("width",x1.rangeBand()).attr("x",function(d){return x1(d.key);}).style("fill",function(d){return colors(d.key);}).attr("id",function(d){return d.key;}).attr("y",function(d){return y(d.value);}).attr("height",function(d){return height-y(d.value);});if(this.isAnimate()){rect.attr("y",function(d){return height;}).attr("height",function(d){return 0;}).transition().duration(1000).attr("height",function(d){return height-y(d.value);}).attr("y",function(d){return y(d.value);});}
this.setTooltip(rect);this.drawAxis();this.drawLegend(this.attrs.labels,true);this.refresh=this;};SBChart.CT.Chart.prototype.stackedBarChart=function(){var data=eval(this.attrs.jsonRef);var svg=this.svg;var x=this.x;var y=this.y;var colors=this.colors;var height=this.height;this.yAxis.tickFormat(d3.format(".2s"));var seriesData=this.createBarData(SBChart.DEF.DATA_VERTICAL);seriesData.forEach(function(d){var y0=0;d.values.forEach(function(d){d.y0=y0;d.y1=y0+=d.value;});d.total=y0;});x.domain(seriesData.map(function(d){return d.category;}));y.domain([0,d3.max(seriesData,function(d){return d.total;})]);var group=svg.selectAll(".g").data(seriesData).enter().append("g").attr("class","g").attr("transform",function(d){return"translate("+x(d.category)+",0)";});var rect=group.selectAll("rect").data(function(d){return d.values;}).enter().append("rect").attr("width",x.rangeBand()).style("fill",function(d){return colors(d.key);}).style("stroke","grey").attr("y",function(d){return y(d.y1);}).attr("height",function(d){return y(d.y0)-y(d.y1);});if(this.isAnimate()){rect.attr("y",function(d){return height;}).attr("height",function(d){return 0;}).transition().duration(1000).attr("height",function(d){return y(d.y0)-y(d.y1);}).attr("y",function(d){return y(d.y1);});}
this.setTooltip(rect);this.drawAxis();this.drawLegend(this.attrs.labels,false);this.refresh=this;};SBChart.CT.Chart.prototype.normalStackedBarChart=function(){var data=eval(this.attrs.jsonRef);var svg=this.svg;var x=this.x;var y=this.y;var colors=this.colors;this.yAxis.tickFormat(d3.format(".0%"));var seriesData=this.createBarData(SBChart.DEF.DATA_VERTICAL);seriesData.forEach(function(d){var y0=0;d.values.forEach(function(d){d.y0=y0;d.y1=y0+=d.value;});d.values.forEach(function(d){d.y0/=y0;d.y1/=y0;d.percent=(d.y1-d.y0)*100;});});x.domain(seriesData.map(function(d){return d.category;}));y.domain([0,1]);var group=svg.selectAll(".g").data(seriesData).enter().append("g").attr("class","g").attr("transform",function(d){return"translate("+x(d.category)+",0)";});var rect=group.selectAll("rect").data(function(d){return d.values;}).enter().append("rect").attr("width",x.rangeBand()).style("fill",function(d){return colors(d.key);}).attr("y",function(d){return y(d.y0)-y(d.y1);}).attr("height",function(d){return y(d.y0)-y(d.y1);});if(this.isAnimate()){rect.attr("y",function(d){return y(d.y0);}).attr("height",function(d){return 0;}).transition().duration(1000).attr("height",function(d){return y(d.y0)-y(d.y1);}).attr("y",function(d){return y(d.y1);});}
this.setTooltip(rect);this.drawAxis();this.drawLegend(this.attrs.labels,false);this.refresh=this;};SBChart.CT.Chart.prototype.verticalBarChart=function(){var x=d3.scale.linear().rangeRound([0,this.width]);var y=d3.scale.ordinal().rangeRoundBands([this.height,this.titleHeight],.1);var xAxis=d3.svg.axis().scale(x).orient(this.attrs.axis.x.orient);var yAxis=d3.svg.axis().scale(y).orient(this.attrs.axis.y.orient);var data=eval(this.attrs.jsonRef);var svg=this.svg;var y1=d3.scale.ordinal();var colors=this.colors;var keys=this.attrs.keys;this.yAxis.tickFormat(d3.format(".2s"));var seriesData=this.createBarData(SBChart.DEF.DATA_VERTICAL);y.domain(seriesData.map(function(d){return d.category;}));y1.domain(keys).rangeRoundBands([0,y.rangeBand()]);x.domain([0,d3.max(seriesData,function(d){return d3.max(d.values,function(d){return d.value;});})]);var group=svg.selectAll(".g").data(seriesData).enter().append("g").attr("class","g").attr("transform",function(d){return"translate(0,"+y(d.category)+")";});var rect=group.selectAll("rect").data(function(d){return d.values;}).enter().append("rect").attr("class","bar").attr("height",y1.rangeBand()).attr("y",function(d){return y1(d.key);}).style("fill",function(d){return colors(d.key);}).attr("x",function(d){return 0;}).attr("width",function(d){return x(d.value);}).attr("id",function(d){return d.key;});if(this.isAnimate()){rect.attr("width",function(d){return 0;}).transition().duration(1000).attr("width",function(d){return x(d.value);});}
this.setTooltip(rect);this.drawVerticalAxis(xAxis,yAxis);this.drawLegend(this.attrs.labels,true);this.refresh=this;};SBChart.CT.Chart.prototype.verticalStackedBarChart=function(){var x=d3.scale.linear().rangeRound([0,this.width]);var y=d3.scale.ordinal().rangeRoundBands([this.height,this.titleHeight],.1);var xAxis=d3.svg.axis().scale(x).orient(this.attrs.axis.x.orient);var yAxis=d3.svg.axis().scale(y).orient(this.attrs.axis.y.orient);var data=eval(this.attrs.jsonRef);var svg=this.svg;var colors=this.colors;var seriesData=this.createBarData(SBChart.DEF.DATA_VERTICAL);seriesData.forEach(function(d){var x0=0;d.values.forEach(function(d){d.x0=x0;d.x1=x0+=d.value;});d.total=x0;});y.domain(seriesData.map(function(d){return d.category;}));x.domain([0,d3.max(seriesData,function(d){return d.values[d.values.length-1].x1;})]);var group=svg.selectAll(".g").data(seriesData).enter().append("g").attr("class","g").attr("transform",function(d){return"translate(0,"+y(d.category)+")";});var rect=group.selectAll("rect").data(function(d){return d.values;}).enter().append("rect").attr("height",y.rangeBand()).style("fill",function(d){return colors(d.key);}).style("stroke","grey").attr("x",function(d){return 0;}).attr("width",function(d){x(d.x1)-x(d.x0);});if(this.isAnimate()){rect.attr("x",function(d){return x(d.x0);}).attr("width",function(d){return 0;}).transition().duration(1000).attr("width",function(d){return x(d.x1)-x(d.x0);});}
this.setTooltip(rect);this.drawVerticalAxis(xAxis,yAxis);this.drawLegend(this.attrs.labels,false);this.refresh=this;};SBChart.CT.Chart.prototype.verticalNormalStackedBarChart=function(){var x=d3.scale.linear().rangeRound([0,this.width]);var y=d3.scale.ordinal().rangeRoundBands([this.height,this.titleHeight],.1);var xAxis=d3.svg.axis().scale(x).orient(this.attrs.axis.x.orient);var yAxis=d3.svg.axis().scale(y).orient(this.attrs.axis.y.orient);var data=eval(this.attrs.jsonRef);var svg=this.svg;var colors=this.colors;var keys=this.attrs.keys;xAxis.tickFormat(d3.format(".0%"));colors.domain(keys);var seriesData=this.createBarData(SBChart.DEF.DATA_VERTICAL);seriesData.forEach(function(d){var x0=0;d.values.forEach(function(d){d.x0=x0;d.x1=x0+=d.value;});d.values.forEach(function(d){d.x0/=x0;d.x1/=x0;d.percent=(d.x1-d.x0)*100;});});y.domain(seriesData.map(function(d){return d.category;}));x.domain([0,1]);var group=svg.selectAll(".g").data(seriesData).enter().append("g").attr("class","g").attr("transform",function(d){return"translate(0,"+y(d.category)+")";});var rect=group.selectAll("rect").data(function(d){return d.values;}).enter().append("rect").attr("height",y.rangeBand()).style("fill",function(d){return colors(d.key);}).style("stroke","none").attr("x",function(d){return x(d.x0);}).attr("width",function(d){return x(d.x1)-x(d.x0);});if(this.isAnimate()){rect.attr("x",function(d){return x(d.x0);}).attr("width",function(d){return 0;}).transition().duration(1000).attr("width",function(d){return x(d.x1)-x(d.x0);});}
this.drawVerticalAxis(xAxis,yAxis);this.drawLegend(this.attrs.labels,false);this.setTooltip(rect);this.refresh=this;};SBChart.CT.Chart.prototype.pieChart=function(){var data=eval(this.attrs.jsonRef);var svg=this.svg;var width=this.width;var height=this.height;var colors=this.colors;var keys=this.attrs.keys;var label=this.attrs.label;var radius=Math.min(width,height)/2;var arc=d3.svg.arc().outerRadius(radius-10).innerRadius(0);var pie=d3.layout.pie().sort(null).value(function(d){return d.percent;});var total=0;keys.forEach(function(key){data[0][key]=+data[0][key];total+=+data[0][key];});if(this.isAnimate()==true){var seriesData=[];keys.forEach(function(key){seriesData.push({key:key,percent:1,label:label[key],value:data[0][key],});});var arcs=svg.selectAll(".arc").data(pie(seriesData)).enter().append("g").attr("class","arc").attr("transform","translate("+this.width/2+","+(this.height/2+this.titleHeight)+")");var paths=arcs.append("path").attr("d",arc).style("fill",function(d){return colors(d.data.key);}).each(function(d){this._current=d;});seriesData.forEach(function(d){d.percent=(d.value/total)*100;});arcs.data(pie(seriesData));paths.data(pie(seriesData));paths.transition().duration(1000).attrTween("d",function(a){var i=d3.interpolate(this._current,a);this._current=i(0);return function(t){return arc(i(t));};});var text=arcs.append("text").transition().delay(500).duration(1000).attr("transform",function(d){return"translate("+arc.centroid(d)+")";}).attr("dy",".35em").style("text-anchor","middle").text(function(d){return d.data.percent.toFixed(0)+"%";});}else{var seriesData=[];keys.forEach(function(key){seriesData.push({key:key,percent:(data[0][key]/total)*100,label:label[key],value:data[0][key],});});var arcs=svg.selectAll(".arc").data(pie(seriesData)).enter().append("g").attr("class","arc").attr("transform","translate("+this.width/2+","+(this.height/2+this.titleHeight)+")");var paths=arcs.append("path").attr("d",arc).style("fill",function(d){return colors(d.data.key);});var text=arcs.append("text").attr("transform",function(d){return"translate("+arc.centroid(d)+")";}).attr("dy",".35em").style("text-anchor","middle").text(function(d){return d.data.percent.toFixed(0)+"%";});}
this.drawLegend(this.attrs.labels,false);this.refresh=this;};SBChart.CT.Chart.prototype.donutChart=function(){var data=eval(this.attrs.jsonRef);var svg=this.svg;var width=this.width;var height=this.height;var colors=this.colors;var keys=this.attrs.keys;var label=this.attrs.label;var radius=Math.min(width,height)/2;var arc=d3.svg.arc().outerRadius(radius-10).innerRadius(radius-70);var pie=d3.layout.pie().sort(null).value(function(d){return d.percent;});var total=0;keys.forEach(function(key){data[0][key]=+data[0][key];total+=+data[0][key];});if(this.isAnimate()==true){var seriesData=[];keys.forEach(function(key){seriesData.push({key:key,percent:1,label:label[key],value:data[0][key],});});var arcs=svg.selectAll(".arc").data(pie(seriesData)).enter().append("g").attr("class","arc").attr("transform","translate("+this.width/2+","+(this.height/2+this.titleHeight)+")");;var paths=arcs.append("path").attr("d",arc).style("fill",function(d){return colors(d.data.key);}).each(function(d){this._current=d;});seriesData.forEach(function(d){d.percent=(d.value/total)*100;});arcs.data(pie(seriesData));paths.data(pie(seriesData));paths.transition().duration(1000).attrTween("d",function(a){var i=d3.interpolate(this._current,a);this._current=i(0);return function(t){return arc(i(t));};});arcs.append("text").transition().delay(500).duration(1000).attr("transform",function(d){return"translate("+arc.centroid(d)+")";}).attr("dy",".35em").style("text-anchor","middle").text(function(d){return d.data.percent.toFixed(0)+"%";});}else{var seriesData=[];keys.forEach(function(key){seriesData.push({key:key,percent:(data[0][key]/total)*100,label:label[key],value:data[0][key],});});var arcs=svg.selectAll(".arc").data(pie(seriesData)).enter().append("g").attr("class","arc").attr("transform","translate("+this.width/2+","+(this.height/2+this.titleHeight)+")");var paths=arcs.append("path").attr("d",arc).style("fill",function(d){return colors(d.data.key);});arcs.append("text").attr("transform",function(d){return"translate("+arc.centroid(d)+")";}).attr("dy",".35em").style("text-anchor","middle").text(function(d){return d.data.percent.toFixed(0)+"%";});}
this.drawLegend(this.attrs.labels);this.refresh=this;};SBChart.CT.Chart.prototype.arcTween=function(a){var i=d3.interpolate(this._current,a);this._current=i(0);return function(t){return arc(i(t));};};SBChart.CT.Chart.prototype.areaChart=function(offset){var data=eval(this.attrs.jsonRef);var svg=this.svg;var x=this.x;var y=this.y;var colors=this.colors;var keys=this.attrs.keys;var height=this.height;this.yAxis.tickFormat(d3.format(".2s"));var area=d3.svg.area().interpolate("line").x(function(d){return x(d.category)+x.rangeBand()/2;}).y0(function(d){return y(0);}).y1(function(d){return y(d.value);});colors.domain(keys);var seriesData=this.createData(SBChart.DEF.DATA_VERTICAL);this.x.domain(seriesData[0].values.map(function(d){return d.category;}));this.y.domain([0,d3.max(seriesData,function(c){return d3.max(c.values,function(d){return d.value;});})]);var series=svg.selectAll(".series").data(seriesData).enter().append("g").attr("class","series").attr("id",function(d){return d.key;});series.append("path").attr("class","streamPath").attr("d",function(d){return area(d.values);}).style("fill",function(d){return colors(d.key);}).style("stroke","grey").style("opacity",.9);var seriesPoints=svg.selectAll(".seriesPoints").data(seriesData).enter().append("g").attr("class","seriesPoints").attr("id",function(d){return d.key;});if(this.isAnimate()==true){var c=0;series.attr("transform","translate(0,"+height+") scale(1, 0)").transition().duration(function(d){c++;return c*200;}).attr("transform","translate(0,0) scale(1, 1)");}
this.drawSeriesPoint(seriesPoints);this.drawAxis();this.drawLegend(this.attrs.labels,true);this.refresh=this;};SBChart.CT.Chart.prototype.stackedAreaChart=function(offset){var data=eval(this.attrs.jsonRef);var svg=this.svg;var x=this.x;var y=this.y;var colors=this.colors;var keys=this.attrs.keys;var height=this.height;this.yAxis.tickFormat(d3.format(".2s"));var stack=d3.layout.stack().values(function(d){return d.values;}).x(function(d){return x(d.category)+x.rangeBand()/2;}).y(function(d){return d.value;});var area=d3.svg.area().interpolate("line").x(function(d){return x(d.category)+x.rangeBand()/2;}).y0(function(d){return y(d.y0);}).y1(function(d){return y(d.y0+d.y);});colors.domain(keys);var seriesData=this.createData(SBChart.DEF.DATA_VERTICAL);stack.offset(offset);stack(seriesData);this.x.domain(seriesData[0].values.map(function(d){return d.category;}));this.y.domain([0,d3.max(seriesData,function(c){return d3.max(c.values,function(d){return d.y0+d.y;});})]);var series=svg.selectAll(".series").data(seriesData).enter().append("g").attr("class","series");series.append("path").attr("class","streamPath").attr("d",function(d){return area(d.values);}).style("fill",function(d){return colors(d.key);}).style("stroke","grey").style("opacity",.9);var seriesPoints=svg.selectAll(".seriesPoints").data(seriesData).enter().append("g").attr("class","seriesPoints").attr("id",function(d){return d.key;});if(this.isAnimate()==true){var c=0;series.attr("transform","translate(0,"+height+") scale(1, 0)").transition().duration(function(d){c++;return c*300;}).attr("transform","translate(0,0) scale(1, 1)");}
this.drawSeriesPoint(seriesPoints);this.drawAxis();this.drawLegend(this.attrs.labels,true);this.refresh=this;};SBChart.CT.Chart.prototype.multiChart=function(){var keys=this.attrs.keys;var y=this.y;for(var i=0;i<this.attrs.data.length;i++){var dataInfo=this.attrs.data[i];var type=dataInfo.type;this.attrs.keys=dataInfo.keys;this.y=dataInfo.axis=="y"?this.y:this.y2;if(type=="bar")
this.barChart();else if(type=="sbar")
this.stackedBarChart();else if(type=="nsbar")
this.normalStackedBarChart();else if(type=="line")
this.lineChart("line");else if(type=="spline")
this.lineChart("cardinal");else if(type=="area")
this.areaChart();else if(type=="sarea")
this.stackedAreaChart("zero");else if(type=="strm")
this.stackedAreaChart("wiggle");else if(type=="pie")
this.pieChart();else if(type=="donut")
this.donutChart();}
this.attrs.keys=keys;this.y=y;this.refresh=this;};SBChart.CT.Chart.prototype.scatterChart=function(){var data=eval(this.attrs.jsonRef);var svg=this.svg;var x=this.x;var y=this.y;var colors=this.colors;this.yAxis.tickFormat(d3.format(".2s"));var seriesData=this.createData(SBChart.DEF.DATA_VERTICAL);x.domain(seriesData[0].values.map(function(d){return d.category;}));this.y.domain([0,d3.max(seriesData,function(c){return d3.max(c.values,function(d){return d.value;});})]);var series=svg.selectAll(".series").data(seriesData).enter().append("g").attr("class","series").attr("id",function(d){return d.key;});this.drawSeriesPoint(series);this.drawAxis();this.drawLegend(this.attrs.labels,true);this.refresh=this;};